# Generated by Django 2.0.1 on 2018-06-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0002_projects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(default='completed', max_length=100),
            preserve_default=False,
        ),
    ]
