# Generated by Django 2.0.6 on 2018-07-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0003_projects_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_net', models.CharField(max_length=200)),
                ('volume_net', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='currproject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobster.Projects'),
        ),
    ]
