# Generated by Django 2.0.6 on 2018-07-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0005_auto_20180721_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='waste_type',
            field=models.IntegerField(choices=[(1, 'Incinerable waste'), (2, 'Non-incinerable waste')], default=1),
        ),
    ]
