# Generated by Django 2.0.6 on 2018-08-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0007_projects_h_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='H_3',
        ),
    ]
