# Generated by Django 2.0.6 on 2018-09-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0009_auto_20180827_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='rn_IRAS',
            new_name='rn_iras',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='rn_LMA',
            new_name='rn_lma',
        ),
    ]
