# Generated by Django 2.0.6 on 2018-09-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0010_auto_20180902_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='RN_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn_name', models.CharField(max_length=15)),
                ('rn_spec_activ', models.IntegerField(default=0)),
                ('rn_total_activ', models.IntegerField(default=0)),
                ('rn_half_life', models.IntegerField(default=0)),
                ('rn_emission', models.CharField(max_length=50)),
                ('rn_vllw_class', models.IntegerField(default=0)),
                ('rn_lma', models.IntegerField(default=0)),
                ('rn_embed_limit', models.IntegerField(default=0)),
                ('rn_iras', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_embed_limit',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_emission',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_half_life',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_iras',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_lma',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_spec_activ',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_total_activ',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rn_vllw_class',
        ),
    ]
