# Generated by Django 2.0.6 on 2018-10-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0011_auto_20180902_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RN_List',
            new_name='RNList',
        ),
    ]
