# Generated by Django 2.0.6 on 2018-10-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobster', '0013_rnlist_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnlist',
            name='element_name',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
